version: "3"
services:
  api:
    build:
      context: .
      args:
        - ENV=development
        - PORT=4000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foodito-dev
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/foodito-dev
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:3000
    command: npm run dev

  db:
    environment:
      - POSTGRES_DB=foodito-dev
