version: "3"
services:
  db:
    container_name: db_container
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/data/db
      # - ./src/scripts/migrations/001-initial.sql:/docker-entrypoint-initdb.d/001-initial.sql
  api:
    container_name: api_container
    build: .
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - CONTAINER_NAME=db_container
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

volumes:
  db:
